### ISSUE TITLE
Stock issue

### ISSUE THREAD

**Issue by Andre305** [agadiffe/SambaPOS_4_download#1]
Good day. I came across this and decided to check it out. It works great but when doing stock transactions like entering supplier invoices to add your stock then it won't calculate it.

No stock is being addded after doing stock transactions but the stock goes off when you sell something that has a recipe and then it goes in the minus.

Also the costing is not working.

Thought you would like to know
Kind Regards

**Comment by agadiffe** [comment]
Hi.
I'm not part of the SambaPOS development team.
You should report this issue on their official forum to get help.
